### ISSUE TITLE
Advanced Code-completion for builtins via snippets

### ISSUE THREAD

**Issue by makeartandgames** [shawnlawson/The_Force#28]
Right now I observe nice code-completion for snippets. The dropdown menu gives me clues about the arguments the function takes; then I can select with the arrow keys and when I press enter, the function populates with dummy type-names where I need to put the parameters.

Builtins show up in the code-completion selector, **1. without any parameter clues** and when the user selects them with enter, **2. there are no dummy values.** 

Builtins have overrides, sometimes a lot. I think usually these overrides are just for the different vector (and float) types, rather than optional arguments. Rather than displaying every version of the override, it's probably more desirable to show only one version, with a generic 'dummy type-name.' The glsl documentation I have on hand uses the term 'genType' or 'genDType' for this pseudo-generic type.

This more advanced code-completion for builtins would be very helpful for newcomers, or even oldcomers with cruddy recall. 

Right now builtins are entered as 'keywords' rather than 'snippets.' I suggest they be moved into 'snippets', but with another tag name (so that they are distinguished from snippets). I don't see much point in duplicating the functions as snippets and keywords.

**Comment by shawnlawson** [comment]
Sorry, behind on things, but catching up. I see the sense in not duplicating, it is annoying to have both. 

I'm not quite sure I follow 100% on the parameter naming part for built-ins. So like for a data type, vec4 there should be a snippet: 
``` 
vec4(genType, genType, genType, genType)
```
instead of multiple options:
``` 
vec4(int, int, int, int)
vec4(float, float, float, float)
...
```
for example? And then similarly with overloaded functions. I may need to user test genType or something similar on newer programmers or non-CS-background creative coders and see what the response is.

I will need to see what the ACE editor lets me tag things as when they appear in the autocompletor engine. Part of these are coming from a language definition/syntax file and from a separate snippets file. I will check and see if removing duplicates from the language definition breaks the syntax highlighting - which I suspect is likely. If it does, then I will look into how the autocomplete dictionaries are built to see if I can inject from a separate source that doesn't have duplicates.

**Comment by shawnlawson** [comment]
Updates made on this [commit](https://github.com/shawnlawson/The_Force/commit/d7360b0c86e91fb39a379b26e18bcb8fe0f7fb83)
 May have resolved part 1. Part 2 has a temporary solution that may be clearer for beginner programmers.

**Comment by shawnlawson** [comment]
Closed due to lack of response.
