### ISSUE TITLE
Workshop files

### ISSUE THREAD

**Issue by NeuroWinter** [shawnlawson/The_Force#7]
None of the workshop files work in the live version, I keep getting a error on vec3 saying its not valid.

**Comment by shawnlawson** [comment]
Interesting, the workshop files from here?
https://github.com/shawnlawson/The_Force_Workshop

**Comment by NeuroWinter** [comment]
Yeah they are. Well from the samplesOfShaders folder.

**Comment by shawnlawson** [comment]
Odd, because they seem to work for me. Can you tell me more about your operating system and browser? And, do you copy/paste or open the file? Maybe I can replicate the error.

**Comment by NeuroWinter** [comment]
I copy and paste them. I will try and load them now, but I am using Chrome Version 50.0.2661.75 m, and I am running Windows 10. 

This is what I see:

![image](https://cloud.githubusercontent.com/assets/7663857/14692800/eae63750-07ad-11e6-8db5-693343bf0780.png)

**Comment by shawnlawson** [comment]
OK, took a while, I found the issue, deciding how best to approach it now. 

Since everything worked on the OS X side with the most recent version of Chrome, I rebooted into Windows 8.1 and tested with the most recent version of Chrome. There I was able to replicate the error. 

Basically what's happening is that the D3D compiler doesn't like that we're declaring a vec2 variable with the name uvN and uv when there exists functions in the header I add with the names uvN and uv. 

As a short term fix you should change 
`
vec2 uvN = uvN();
vec2 uv = uv();
`

to any different name or something like
`
vec2 my_uvN = uvN();
vec2 my_uv = uv();
`
and change all other instances of uvN and uv to my_uvN and my_uv. Then everything seems to work.

For the longer term fix, I'll go through both the workshop files and the example shader files in this repo and make a cleaner change so that they work without the short term fix.

**Comment by shawnlawson** [comment]
All example shader files now updated in this repo and the workshop repo to be D3D compliant.
